
dist: xenial
sudo: required
language: cpp

addons:
  apt:
    packages:
      - libsdl2-dev
  homebrew:
    packages:
      - sdl2
    update: true

os:
   - linux
   - osx

compiler:
   - clang
   - gcc

matrix:
   exclude:
   - os: linux
     compiler: clang
   - os: osx
     compiler: gcc

script:
   - mkdir build
   - cd build
   - cmake ..
   - make package

