
dist: xenial
sudo: required
language: cpp

addons:
  apt:
    packages:
      - libsdl2-dev

before_install:
   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2; fi

os:
   - linux
   - osx

compiler:
   - clang
   - gcc

matrix:
   exclude:
   - os: linux
     compiler: clang
   - os: osx
     compiler: gcc

script:
   - mkdir build
   - cd build
   - cmake ..
   - make package

